### ISSUE TITLE
Curricular aspects of Maintainer Onboarding

### ISSUE THREAD

**Issue by ccronje** [LibraryCarpentry/governance#10]
## Introduction
The Library Carpentry curriculum has come a long way! The bulk of the lessons began in this [GitHub organisation](https://github.com/data-lessons) before moving [here](https://github.com/LibraryCarpentry). In 2016, the community starting participating in the Mozilla Science Lab Global Sprints (see [2016](https://software-carpentry.org/blog/2016/06/library-carpentry-sprint.html), [2017](https://software-carpentry.org/blog/2017/06/lc-sprint.html), [2018](https://librarycarpentry.org/blog/2018/05/our-latest-sprint/)) - coming together annually to focus on lesson and curriculum development. Throughout the rest of the year, maintainers for each lesson look after issues and pull requests that come in as a result of feedback from learners and instructors. In late 2018, [Library Carpentry merged with The Carpentries](https://carpentries.org/blog/2018/11/welcoming-library-carpentry/) as an official lesson program, which means that curriculum development will be changing, gradually adopting processes outlined in the [Maintainer Onboarding lesson](https://carpentries.github.io/maintainer-onboarding/) and [The Carpentries Handbook](https://docs.carpentries.org/topic_folders/maintainers/index.html). The following summary is designed to provide some background to processes 'pre-merge' (what exists currently) and 'post-merge' (what we are aiming for in the future) to help this transition.

**Comment by ccronje** [comment]
## Maintainers and lessons
Previously, maintainers for Library Carpentry lessons have come together organically, based on their interest in the lesson topic and their availability to keep an eye on issues and pull requests. In some cases, maintainers have been looking after lessons for years (happily!). This is not sustainable however, and recently a call went out for new maintainers. This process will continue on a yearly basis to relieve current maintainers and give others an opportunity to be involved. As a result of the merge with The Carpentries (see [Introduction](https://github.com/LibraryCarpentry/governance/issues/10#issue-379093290), a [Curriculum Advisory Committee](https://librarycarpentry.org/blog/2018/08/library-carpentry-cac/) was formed to ensure maintainers are supported, to help transition to new processes post-merge, and to facilitate any major changes to the curriculum. The committee's full responsibilities are outlined [here in The Carpentry's Handbook](https://docs.carpentries.org/topic_folders/lesson_development/lesson_development_roles.html#curriculum-advisory-committee).

### Current maintainers
Current Library Carpentry maintainers are listed [here](https://docs.google.com/spreadsheets/d/18rNY0LOf8zUzMMilWzh-vmhukL_Ty6hu3_nngkyCmus/edit#gid=0), and in each lesson repository.

### Current lessons
Current lessons are listed on the [Library Carpentry website](https://librarycarpentry.org/lessons/). This is the best place for people to start exploring the curriculum.

**Comment by ccronje** [comment]
## Current processes for maintainers
Your role as a maintainer will vary depending on the maturity of the lesson you maintain. There are at least two maintainers per lesson (see the list of [current maintainers](https://docs.google.com/spreadsheets/d/18rNY0LOf8zUzMMilWzh-vmhukL_Ty6hu3_nngkyCmus/edit#gid=0)). The [Maintainer Onboarding lesson](https://carpentries.github.io/maintainer-onboarding/02-curricular/index.html) discusses processes (e.g. Issue Bonaza, Bug BBQ) that haven't been implemented in Library Carpentry yet. Don't worry, this will develop over time. To chat with other Carpentries maintainers, register on Slack and Topic Box (see [Important links](https://github.com/LibraryCarpentry/governance/issues/10#issuecomment-453713612)).

### To get started as a maintainer:
* Have a look through the current issues and pull requests in your lesson's repository.
* If the issue or pull request is a minor change like a typo, it can be resolved and the issue/pull request can be closed by you.
* If it's more complicated [add an appropriate label](https://docs.carpentries.org/topic_folders/maintainers/github_labels.html). See [creating lables in GitHub](https://help.github.com/articles/creating-a-label/).
* If you need another set of eyes over the issue or pull request [add a reviewer](https://help.github.com/articles/requesting-a-pull-request-review/) and/or ping the appropriate person by including their github handle (e.g. @ccronje) in a comment.

### A good weekly habit:
* [Watch your lesson's repository](https://help.github.com/articles/watching-and-unwatching-repositories/).
* Review new issues and pull requests.
* Keep progressing older issues and pull requests by pinging appropriate people in a new comment (be mindful that things take time in a community of volunteers!).
* Register with [The Carpentries Maintainers Slack channel](https://swcarpentry.slack.com/messages/C8H5LN44V/details/) to keep an eye on discussions, or to raise any questions you have.

### Useful news channels:
* If you're on Twitter, follow https://twitter.com/LibCarpentry and https://twitter.com/thecarpentries.
* Sign up for the monthly [Carpentries newsletter](https://carpentries.org/newsletter/).

**Comment by ccronje** [comment]
## Important links
[Maintainer Onboarding](https://carpentries.github.io/maintainer-onboarding/index.html)
[Lesson Maintenance - The Carpentries Handbook](https://docs.carpentries.org/topic_folders/maintainers/index.html)
[Library Carpentry lessons](https://librarycarpentry.org/lessons/)
[Maintainers channel - The Carpentries Slack team](https://swcarpentry.slack.com/messages/C8H5LN44V/details/)
[Maintainers channel - The Carpentries Topic Box (replaces google groups)](https://carpentries.topicbox.com/groups/maintainers)
[Maintainers meetings (not compulsory)](https://pad.carpentries.org/maintainers)

**Comment by libcce** [comment]
I think we can close this now that the onboarding has concluded, see  https://github.com/LibraryCarpentry/governance/blob/master/curriculum/2019-01-20-summary-maintainer-discussions.md
