### ISSUE TITLE
Determine what 'menus' would look like for 1- and 2-day LC workshops?

### ISSUE THREAD

**Issue by PhilReedData** [LibraryCarpentry/governance#14]
At CarpentryConnect 2019 we held a workshop 'Strengthening the Library Carpentry community'. One action that arose was to develop two to three ‘set menus’, and articulate what a 1-day LC workshop involves compared to a 2-day LC workshop. 

I shall share a link to the write-up as soon as it is published. ([Workshop plan](https://docs.google.com/document/d/1GtGYyNJ5k8CX2A8LxsLVbwFYS2eRdY5XtRnk5X9aHQc/edit#heading=h.iwu4wis800d6), [Etherpad](https://pad.carpentries.org/ccmcr19-strong-lc ), [Blog draft](https://docs.google.com/document/d/1ipfgtwQAFTQESlBxwbaTAYaq2bwxy5zvf_qQqHNzczU/edit)

**Comment by davidfkane** [comment]
Hi Phil,

Thanks for sharing this with us.  I did not manage to get to Manchester this year.  We ran a Carpentries instructor onboarding workshop and then went to LIBER.  I have wanted to get in touch with a couple of people who went to the conference to get a feel for what was going on.

Kind regards,

David Kane

**Comment by PhilReedData** [comment]
From Chris Erdmann: "One that has proven to be effective is a half day on OpenRefine and an intro to what LC is. This has been run many times and has been effective so I think we would be ready for a Curriculum Advisory Council vote to make this standard."

**Comment by libcce** [comment]
Thanks @PhilReedData! The Curriculum Advisory Committee helps with what you are calling "set menus" or curriculums https://librarycarpentry.org/cac/ I think we were in a waiting pattern as some of the lessons needed to be developed further. For instance, Tidy Data is a fork of a Data Carpentry lesson and needs to be updated to the Library Context. However, having said that, from what I am seeing from the community, I see us wanting to move these menus forward:

- 1/2 day OpenRefine w/ intro to LC
- 1-day Intro to Data, Tidy Data, OpenRefine
- 2-day Intro to Data, Shell, Git, OpenRefine
- 2-day Intro to Data, Shell, Python, OpenRefine
- 2-day Intro to Data, Shell, Python, Git

These menus have already been offered a fair number of times. The question then is, what are the major concepts that we want to convey and teach in these menus and we can probably reach out to the instructors to find out why they decided on those combinations. 

Ideas for menus that are still very fresh:
- Data Intro, Tidy Data, OpenRefine, SQL
- Intro to Data, Tidy Data, OpenRefine, Git, FAIR

Where are we at with the lessons:
- Intro to Data is stable but we are updating the lesson (in the next 2-3 months) to account for some of the feedback we've heard from instructors
- OpenRefine is very stable and we only have minor improvements to make/nothing major
- The UNIX Shell is also very stable and the Maintainers are working on incorporating more library examples/exercises at the tail end of the lesson
- The Maintainers had philosophical conversations about teaching Git but we are moving in a direction of a GitHub first approach, then moving to the command line using a thesis/dissertation/paper writing scenario to frame the lesson (it will take 4-5 months possibly before its ready)... but the current lesson is stable and has been taught many times
- Tidy Data is a fork and needs the library context to be updated (it will take 4-5 months possibly)
- SQL is close to being stable (another 2-3 months)
- FAIR/Wikidata are still pre-alpha but there is a lot of momentum around these lessons and there is some content to work with at the moment (a pilot FAIR lesson was run at one institution and well received)
- Webscraping has only been taught once but we just got another request for it... the Maintainers have been updating it and it seems moderately stable.
- The Maintainers have decided to go back to the drawing board with the Python lesson and take a more data-centric approach to teaching it (for instance, working with CSVs, pandas)... it is set to alpha... but the current lesson definitely can be taught and has been taught many times.

My question is, are we prepared to create set menus when some of these lessons are in flux. I'd feel comfortable with introducing the "OpenRefine & LC Intro" menu and then announcing to the community that we are exploring these other options while the lessons are being further refined/developed. What do our CAC members @jt14den @ccronje @katrinleinweber @laufers @erikamias think?

**Comment by ccronje** [comment]
Have started a new curricula table in https://librarycarpentry.org/lc-overview/
Will need to seek further feedback from LC community regarding workshops taught.

**Comment by ccronje** [comment]
Ties in with https://github.com/LibraryCarpentry/governance/issues/25
