### ISSUE TITLE
Improve language of 'days' vs 'parts' across workshops

### ISSUE THREAD

**Issue by PhilReedData** [LibraryCarpentry/governance#15]
Following the CarpentryConnect 2019 workshop on strengthening LC, @libcce has pointed me to a [comment](https://github.com/LibraryCarpentry/governance/issues/13#issuecomment-504539533) about our good use of 'parts' instead of 'days' in lessons. Our workshops may span four afternoons/evening, rather than two full, consecutive days; they are more flexible than many SWC or DC workshops in that way.

I'm not sure if this good practice has been applied across all the LC lessons. Perhaps we should check this and any similar improvements which could be made.

**Comment by ccronje** [comment]
Addressed in https://librarycarpentry.org/lc-overview/
