### ISSUE TITLE
New LC Curricula / Language / Workshop Offerings

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/governance#16]
Hi @jt14den @ccronje @katrinleinweber @laufers @erikamias,
 
At CarpentryConnect in Manchester, and also in the Advisory Group, members of our community have asked for updates to the LC curriculum. I’ve posted this comment in the governance repo and shared my thoughts/updates:
 
https://github.com/LibraryCarpentry/governance/issues/14#issuecomment-509286378
 
At the moment, my recommendation would be to offer a new curriculum called _Introduction to Library Carpentry & OpenRefine_. There have been a number of cases where libraries have offered only OpenRefine and provided a short introduction to Library Carpentry. 
 
We can also consider offering the following curriculum which have been taught a number of times as well:
 
- _Intro to Data, Shell, Python, OpenRefine_
- _Intro to Data, Shell, Python, Git_
 
I can restructure the layout of the lessons page to list these curricula:
https://librarycarpentry.org/lessons/
 
I can also update The Carpentries Team to add these curricula to the request a workshop form.
 
We will have to include language per:
https://github.com/LibraryCarpentry/governance/issues/15.
 
Carmi, Katrin, Mark, Erika, Tim, can you please vote on:

- [ ] Add _Introduction to Library Carpentry & OpenRefine_ curriculum to the lessons page
- [ ] Add _Intro to Data, Shell, Python, OpenRefine_ curriculum to the lessons page
- [ ] Add _Intro to Data, Shell, Python, Git_ curriculum to the lessons page
- [ ] Add flexibility language, ‘parts’ vs ‘days’, taught over weeks/months to the lessons page/curricula
- [ ] Submit new curriculum to Carpentries Team

We can revisit the curriculum that includes Tidy Data and SQL later when the lessons are stable.
 
Thank you,
Chris

**Comment by katrinleinweber** [comment]
I don't have any feelings this way or that about those votes. If the majority agrees with these changes, I support them, too.

**Comment by erikamias** [comment]
I support the menu and workshop flexibility language update. 

I suggest adding "Intro to Data, Shell, Open Refine, Git/Github" as a menu option as well, it's a menu that's been used before or is it not that popular anymore? In which case then it's not worth adding it.

Might also be a good idea to explain the "Introduction to Library Carpentry" part of "Introduction to Library Carpentry and OpenRefine" is not a lesson itself but a general/short introduction to what LC is about? Maybe a link to some basic presentation slides that can be adapted?

**Comment by libcce** [comment]
Thanks for catching that @erikamias that we should also include the standard workshop: Intro to Data, Shell, OpenRefine, Git/GitHub. We will add that to the list.

There are slides for the introduction to LC. I only worry about keeping them fresh but maybe that is part of the language we will use about helping to keep the slides fresh/that they may need to be updated.

Thanks @erikamias !

**Comment by pherterich** [comment]
I had a colleague asking for OpenRefine and MarcEdit (which doesn't exist yet) as a combination for teams where the shell and git isn't really that useful, so the solution was to do organise a carpentry inspired training day on OpenRefine but not actually run a Library Carpentry workshop.
In addition, I ran a friendly GitHub session for them, again avoiding command line but providing an idea of why GitHub is useful. https://pherterich.github.io/friendly-github-intro/

**Comment by libcce** [comment]
Thanks @pherterich! 
- MarcEdit has come up before. Do you have some pointers to material that you've found useful? In order to put a lesson together on MarcEdit, we need an individual/group that is inspired to take the time to develop the lesson. Do you know of anyone? 
- Thanks, your feedback on OpenRefine further supports a separate OpenRefine offering. 
- Any feedback to share from your GitHub training? I believe you've seen where the LC git lesson Maintainers are going with the lesson after receiving feedback from instructors. Would be nice to have your feedback as well.

**Comment by ostephens** [comment]
I think we've been reluctant to include MarcEdit as the focus of a lesson because it isn't Open Source. 

That said, I've taught MarcEdit alongside OpenRefine in non-carpentry workshops. I've published the handout I wrote for this as CC-BY http://www.meanboyfriend.com/overdue_ideas/wp-content/uploads/2019/08/MarcEdit-Handout-1.pdf if that's of any interest

**Comment by libcce** [comment]
@ostephens I haven't looked at MarcEdit in a while but seems like it is more open than Matlab https://marcedit.reeset.net/marcedit-end-user-license-agreement which is a lesson in The Carpentries. I feel another reason is that maybe our philosophy was to hopefully move away from using MarcEdit via the LC curriculum/lessons? But having said this, your handout is a pretty good outline for a lesson and seems like it could be useful to move it to a (pre-)alpha lesson? @pherterich thoughts?

**Comment by ostephens** [comment]
If we were to offer OpenRefine and MarcEdit I'd be in favour of it being in combination with at least Intro to Data as that includes Regular Expressions which we use without further introduction in the OpenRefine lesson and I'd suggest the same approach with MarcEdit

**Comment by davidfkane** [comment]
I've just been asked for advice on who can teach a library carpentry sesson on OpenRefine and MarcEdit by a group in the UK.  MarcEdit is a significant tool in the library world and I would like to see a structured lesson on its use.  P.S. I strongly recommended you, Owen, having been to one of your training sessions on MarcEdit & OpenRefine in Dublin.

**Comment by pherterich** [comment]
Sorry, was on honeymoon and just manage to catch up now. I'm pretty sure the group that contacted @davidfkane is my colleague following up on our chat :smile: 
I don't have experience with using MarcEdit but from what I understood from colleagues, it is fairly crucial to cataloguers and I got the impression that they would prioritize it over any Library Carpentry session. 
Intro to Data + Some MarcEdit + OpenRefine with a focus on where it could replace MarcEdit (I don't have enough knowledge to judge if that makes sense) sounds like a reasonable menu to me that maybe @ostephens could trial with the UK group?

**Comment by libcce** [comment]
Hi @pherterich congratulations 🎉 I'm back from leave but now @ostephens is on vacation 🌴 But before he left, @jt14den launched this repo https://github.com/LibraryCarpentry/lc-marcedit and we are waiting until @ostephens gets back to move his material over to jumpstart the lesson. We will need Maintainers on the lesson, so if you @davidfkane know of anyone that wants to help then let us know. We are also thinking of inviting the MarcEdit lead developer as a Maintainer as well.

**Comment by ccronje** [comment]
Have started a new curricula table in https://librarycarpentry.org/lc-overview/
