### ISSUE TITLE
Proposal to merge the CAC with the Advisory Group

### ISSUE THREAD

**Issue by ccronje** [LibraryCarpentry/governance#18]
Hi All
 
As you may be aware, we've had a few changes in the LC community recently, including the departure of Chris Erdmann, Katrin Leinweber stepping down as Chair of the Curriculum Advisory Committee, and a few members leaving due to other commitments. This has prompted discussion in the CAC about how we best proceed in maintaining a governance group around the curriculum.

We would like to propose merging with the Advisory Group, and forming a curriculum subgroup. We think there is a significant overlap of interest in the groups, and having one main entity and driving force would be more efficient. We would also like to provide opportunities for others to step into the role/group, and rotate members more easily.

I've raised this issue to vote on the proposal with thumbs up/comments. Could the Advisory Group please let us know if they are in favour of the proposal to merge?

Many thanks
Carmi Cronje

**Comment by libcce** [comment]
@ccronje I’m in favor. Which members from the CAC will be staying on to join us? This aligns with our current goal-group structure. Wondering if the CAC should be a co-chair, if it helps with the transition? But I think this is a good idea 😀

**Comment by Jaredabera** [comment]
I do support the idea of merging together or synergy in the community. And best of luck to both Chris Erdmann, Katrin Leinweber to their new commitments. They have taken some interesting changes in the community specially in inviting peoples from different geographical location and scientific background on board and I thank you for your courageous steps in giving everyone an opportunity. Chris Erdmann I personally thank you man.

**Comment by libcce** [comment]
Thanks @Jaredabera!!!

**Comment by ragamouf** [comment]
Thanks @ccronje! I'm in favour of this proposal. Also, I think having 2 x co-chairs for the merged group would be helpful for managing the complexity.

**Comment by konrad** [comment]
Sound also good for me. Thanks for suggestion this, @ccronje.

**Comment by arieldeardorff** [comment]
Hi all,

I am also in favor of merging as it seems like there is a lot of overlap in our scope. As the current chair of the Advisory Group I would definitely welcome a co-chair :)

**Comment by jt14den** [comment]
I'm in favor of merging the groups.

**Comment by goldmj** [comment]
The merger sounds good to me.

**Comment by ccronje** [comment]
Thanks everyone for the positive response! Having 2x co-chairs is an excellent idea. I am currently acting as chair since Katrin's departure, and would like to step back from the role but continue in the merged group.

We've had a few recent changes in the CAC:
- @erikamias will be leaving us
- @PhilReedData has joined us
- @jt14den and @laufers can you please let us know if you would like to continue in the merged group?

For those interested in becoming a co-chair, can you please reply below?

**Comment by laufers** [comment]
I would like to continue in some role with the merged group. 

-Mark

**Comment by ragamouf** [comment]
Hi Carmi, I'm interested in becoming a co-chair, but think it's important to have at least one co-chair from the previous Curriculum Advisory Committee. Maybe we could have 3 in the style of Research Data Alliance groups?

**Comment by ccronje** [comment]
Fantastic, thanks for nominating @ragamouf! Pending @jt14den's reply I can triple up with you for a while, good idea.

**I would also welcome nominations below (or thumbs up to this comment) - who would like to be in the new subgroup?**

**Comment by libcce** [comment]
It will be great to have @ragamouf as a 2nd chair 👍 I'll also (re)join the subgroup.

**Comment by arieldeardorff** [comment]
Hi All! It looks like we have a pretty good consensus about merging our two groups, with myself, @ccronje and @ragamouf acting as new co-chairs. At this point maybe the three of us should set up a brief chat with @elizabethwilliams8 to make sure we are all on the same page about next steps and to take care of any back end business (updating the website, etc). Sound good?

**Comment by ccronje** [comment]
Thanks @arieldeardorff that sounds good 👍

**Comment by ragamouf** [comment]
I agree too - do any of these times work for you? 
This week: (Sydney Fri 8th Nov/ US Thurs 7th Nov)
<img width="418" alt="Screen Shot 2019-11-05 at 10 02 09 am" src="https://user-images.githubusercontent.com/46695862/68165390-6d549780-ffb3-11e9-8d9a-4a41b9c0e640.png">
Next week: (Sydney Tues 12th Nov/ US Mon 11th Nov)
<img width="476" alt="Screen Shot 2019-11-05 at 9 52 00 am" src="https://user-images.githubusercontent.com/46695862/68165379-66c62000-ffb3-11e9-910b-5bf340109ce2.png">

**Comment by arieldeardorff** [comment]
I can do all those times except for the first one (Thu 4pm SF).

**Comment by ccronje** [comment]
I can only do the third one Tue 10am Sydney

**Comment by arieldeardorff** [comment]
@elizabethwilliams8 does the Tue 10am Sydney/Mon 3pm SF work for you? If not I can also send out a larger poll.

**Comment by elizabethwilliams8** [comment]
Monday at 3 Pacific is great! Thank you, looking forward to talking with
you all! I can go ahead and send out a calendar invitation.

Best,
*Elizabeth Williams*
Director of Membership
Twitter: @ecwilliams8 <https://twitter.com/ecwilliams8>
Pronouns: any pronoun acceptable
*The Carpentries |* www.carpentries.org

Schedule a meeting with me: https://calendly.com/ecwilliams8

The Carpentries <https://carpentries.org/> *- **We teach foundational
coding and data science skills to researchers worldwide.*
Twitter <http://twitter.com/thecarpentries> | Facebook
<https://www.facebook.com/carpentries/> | Blog
<https://carpentries.org/blog/>

The Carpentries is a fiscally sponsored project of Community Initiatives
<http://communityin.org/>, a registered 501(c)3 non-profit organisation
based in California, USA.
We are a global community teaching foundational computational and data
science skills to researchers in academia, industry and government.

**Comment by elizabethwilliams8** [comment]
I sent a google calendar invitation that includes a link to my zoom room,
which we can use for the meeting: https://carpentries.zoom.us/j/6082271917

*Elizabeth Williams*
Director of Membership
Twitter: @ecwilliams8 <https://twitter.com/ecwilliams8>
Pronouns: any pronoun acceptable
*The Carpentries |* www.carpentries.org

Schedule a meeting with me: https://calendly.com/ecwilliams8

The Carpentries <https://carpentries.org/> *- **We teach foundational
coding and data science skills to researchers worldwide.*
Twitter <http://twitter.com/thecarpentries> | Facebook
<https://www.facebook.com/carpentries/> | Blog
<https://carpentries.org/blog/>

The Carpentries is a fiscally sponsored project of Community Initiatives
<http://communityin.org/>, a registered 501(c)3 non-profit organisation
based in California, USA.
We are a global community teaching foundational computational and data
science skills to researchers in academia, industry and government.

**Comment by ccronje** [comment]
liz.stokes
2 Dec (1 day ago)
Actions
Hi all,

The results are in! 12 people voted in our formal poll with 100% agreement to include the Library Carpentry Curriculum Advisory Committee as a sub-committee of the Library Carpentry Advisory Group (LCAG), effectively merging the two groups.

Thanks to everyone who voted. Let's keep the momentum going by extending a warm welcome to new members of the Advisory Group, and heartfelt thanks to the wonderful people who have been part of and carried the LCAG and Curriculum Advisory Committee this far - Chris Erdmann, Katrin Leinweber and Erika Maas.

Ariel and Liz will proceed in 2020 as co-chairs of the LCAG, and Liz will chair the Curriculum Subcommittee as Carmi Cronje seeks to step back a little. We'll be changing the information on the website to reflect this decision - please let us know if you want to remain/join the Curriculum Advisory Committee.

In terms of bringing us all together, we would like to propose a new meeting date for the next LCAG, (Liz is unavailable on Thurs 16th Jan, 2020). Please complete this doodle poll  by Friday 6 December for us to start this daunting process of aligning timezones.  Sincere apologies in advance - none of the times are great for everyone!

As Ariel has mentioned, previous Curriculum Committee members are welcome to contribute to any of our goals so do feel free to jump in to any mini goal issues in the governance repo.

There's also a flagged action from the last LCAG meeting which would definitely benefit from everyone's input:
- take a look at the workshop overview and intro lessons and share feedback by opening an issue.

See the LCAG pad for previous meeting notes https://pad.carpentries.org/lc-advisory-group

very best regards,
Liz Stokes & Ariel Deardorff
LCAG Co-chairs
