### ISSUE TITLE
Library Carpentry Workshop Overview Page

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/governance#2]
Based on the Data Carpentry Workshop Overview Page http://www.datacarpentry.org/ecology-workshop/, I've created this rough draft for community input on the Library Carpentry overview page:

https://librarycarpentry.github.io/lc-overview/
https://github.com/LibraryCarpentry/lc-overview

Please add your feedback via issue(s) or via PR(s).

Thanks to @cmacdonell for your help!

**Comment by libcce** [comment]
Based on the June 11 governance call, we decided that the overview page should speak to a 2-day timeframe (or 12 hours). A 2nd overview page will be created called "Express Library Carpentry" based on some of @weaverbel's work, e.g. https://weaverbel.github.io/2018-07-12-auckland/. An express workshop can include jargon busting, an abbreviated lesson, overview of a full LC workshop, and discussion. Language will be added to explain that the delivery modes for the workshops can be entirely flexible and can be according to local needs. This is to encourage and not limit workshops. For the 2-day workshop, language will be added to Part 2 that speaks to the exploration of other automation language lessons, Python, R, to be substitutes.

**Comment by katrinleinweber** [comment]
Hi! I'm late to this issue, sorry. Maybe we don't have to set up two additional pages, but upgrade the main site with a kind of "lasso" overlay that groups the "express" lessons, like so:

![image](https://user-images.githubusercontent.com/9948149/41314036-d24dcc02-6e8b-11e8-80c5-202c7869c9d2.png)

Does anyone know whether the website template has a plugin like that? If yes, we could also group / annotate the lesson statuses that way: different colored "lassos".

**Comment by libcce** [comment]
Hi @katrinleinweber! I think we can include the overview on the website as well. @tracykteal has suggested we develop this overview page (based on the ecology workshop overview page) for instructor training purposes and for our community.

**Comment by Kakaalikins** [comment]
The overview reads well for me. Thanks @libcce! Are we going to add information about about the required format and compulsory lessons?

@katrinleinweber Please pop me a mail: kay@figshare.com ? I completely forgot your address and want to clarify that DOI thing :)

**Comment by libcce** [comment]
That language will be included but we also have to combine that with language that encourages flexibility. As @weaverbel said, we want to encourage people to host workshops and not sound too restrictive.

**Comment by katrinleinweber** [comment]
> I think we can include the overview on the website as well.

The [website already has an overview: that grid](http://librarycarpentry.org/#portfolioModal8). Is the goal of maintaing almost same info in two places to have one version for the general public and one for "us"?

**Comment by libcce** [comment]
New website launched https://librarycarpentry.org/ where our workshops and lessons address this issue
