### ISSUE TITLE
Goal 3 Mini Group: Outreach to 5 Library Networks

### ISSUE THREAD

**Issue by arieldeardorff** [LibraryCarpentry/governance#20]
Hi All! Starting this issue so we can have a way to chat about what we have been working on. As a reminder we are thinking about library groups where we might want to present/share information on Library Carpentry. Thanks to @davidfkane for agreeing to chair this mini group! I have copied the notes that he sent out here so we have one place to reference them. 

- Networks we will reach out to: https://docs.google.com/document/d/1IQgVWUlwm8xm3P5ra713C2LGhGaAkiSX4mY9hmklVX8/edit?usp=sharing  

- Slides we will provide following the conversation: https://docs.google.com/presentation/d/1sLDfiybPrSRO9uiOzHdxjAgrC612umMU5l4nhjJ8TAM/edit#slide=id.g4d033d70c5_0_335

- Other slides we can use: https://librarycarpentry.org/lc-overview/02-intro-to-library-carpentry/index.html

- The spreadsheet we will use to log conversations: https://docs.google.com/spreadsheets/d/1NPSthWzIQIvrz9RRl-ErQBqJnn9SD0ikkJ5Zpz6mLog/edit#gid=0

Group Members:
@chodacki @goldmj @davidfkane @elibtronic @gitti1 myself

**Comment by arieldeardorff** [comment]
I was thinking about proposing a webinar for the [Medical Library Association](https://www.mlanet.org/) but I am not sure that is the best format for Lib Carpentry outreach (mostly because they cost money and that made me feel a little weird). Recently someone brought up the idea of MLA Continuing Ed credit for our workshops so now I am looking more into that.

I also just got an email from the [National Network of Libraries of Medicine](https://nnlm.gov/) who wanted to chat more about collaborating. It looks like @goldmj and @libcce presented an NNLM webinar back in the day, would either of you be interested in joining a call with me and Jessi Van Den Volgen or should I just report back?

**Comment by goldmj** [comment]
Happy to join a call with NNLM - am definitely interested how NNLM can support more regular LC programming - either workshops in various regions or webinars.

**Comment by libcce** [comment]
Count me in!

**Comment by elibtronic** [comment]
Hi All. I've arranged a session with the Ontario Library Association for April.
Details here: 
https://brockdsl.github.io/2020-04-29-Ryerson/

**Comment by arieldeardorff** [comment]
> Hi All. I've arranged a session with the Ontario Library Association for April.
> Details here:
> https://brockdsl.github.io/2020-04-29-Ryerson/

Is this still happening @elibtronic ?

**Comment by arieldeardorff** [comment]
Hi All! Several of us did end up reaching out to various library groups this year - maybe we can share out here and then close this issue. 

I did some outreach work with the Network of the National Library of Medicine (which is hosting 5 LC workshops and 1 instructor training) and held several outreach conversations with University of California and California State University Librarians (who have been busy collaborating and co-teaching this past year).

**Comment by ragamouf** [comment]
Probably our recent LCAG meeting minutes contain the best summary we're likely to get. I'll raise this at the next meeting in May so we can set timeframes and expectations about 2021 outreach.
