### ISSUE TITLE
Proposal for Librarians Building Momentum for Reproducibility

### ISSUE THREAD

**Issue by goldmj** [LibraryCarpentry/governance#21]
Hi all, 

Upcoming virtual conference, [Librarians Building Momentum for Reproducibility ](https://vickysteeves.gitlab.io/librarians-reproducibility/) in January.

Looking for anyone up for co-presenting with me on Library Carpentry - what we are all about, maybe including some of our goals, and/or a demo of a lesson. @libcce and I have already worked on some previous presentations we can pull from, and on one webinar we did an OpenRefine demo and I think it went really well.

See more on the [CFP](https://vickysteeves.gitlab.io/librarians-reproducibility/cfp/). 

It would be great to know if you are interested by **Monday November 25** so I can get something submitted December 2 - sorry the Thanksgiving Holiday in the US makes this a time sensitive issue!

**Comment by libcce** [comment]
I can help @goldmj 👍

**Comment by jcoliver** [comment]
I'm happy to contribute as well.

**Comment by goldmj** [comment]
Awesome @jcoliver @libcce 
I have started a proposal here (pulling from previous work): https://docs.google.com/document/d/1JtuGpO3geF3lI2NDGmdC6CxAb78xLlHIS5izmE8ypeM/edit?usp=sharing
Please contribute!

**Comment by goldmj** [comment]
Incorporated the feedback into the proposal - thanks all!
Took the topics suggested by Jeff and focused the presentation outline on those: (1) the reproducibility tools included in LC workshops (e.g. OpenRefine, Dates, Intro to Data), (2) the emphasis on LC instructional practices (e.g. live 'coding', peer-to-peer learning), and (3) the necessity of a data savvy workforce in the library.
Please review!!

**Comment by jcoliver** [comment]
Thanks for putting this together, @goldmj! I made a couple of tweaks to the abstract. Still have more room (~75 words) if there are glaring omissions.

**Comment by goldmj** [comment]
@libcce @jcoliver This is embarrassing, but I realize I never actually submitted this! Totally dropped the ball and I really apologize . So we can think of another place to submit this to!

**Comment by libcce** [comment]
Ha! No worries @goldmj 😄 It's the thought that counts!

**Comment by ccronje** [comment]
That looks terrific @goldmj @libcce @jcoliver. Would you consider remote participation in https://www.rd-alliance.org/plenaries/rda-15th-plenary-meeting-australia? In particular the Libraries for Research Data Interest Group https://www.rd-alliance.org/libraries-building-bridges-capacities-updates-discussion-current-topics

**Comment by jcoliver** [comment]
Bwahaha! The Coalition for Networked Information has a CFP for their Spring 2020 meeting at https://www.cni.org/events/membership-meetings/upcoming-meeting/spring-2020

**Comment by goldmj** [comment]
@jcoliver I cant make it to San Diego (as much as I would LOVE to!) but if someone else is thinking of going...

**Comment by goldmj** [comment]
@ccronje remote participation could work depending on the day - this is right after RDAP in NM - let's discuss!

**Comment by jcoliver** [comment]
I'm putting in a separate CNI proposal, but maybe some of our California denizens (like @jt14den or @arieldeardorff or @chodacki ) could be convinced?

**Comment by arieldeardorff** [comment]
Hey All! It looks like there was a Software Carpentry presentation at CNI back in 2017: https://www.cni.org/topics/teaching-learning/software-carpentry-in-the-library-partnering-to-give-researchers-needed-technical-skills but it wasn't focused on teaching librarians and it has been a couple years so we could probably submit again. @jt14den San Diego is close to you...

**Comment by libcce** [comment]
Some other people to involve from UCSD @U2NG @stephlabou 😄

**Comment by libcce** [comment]
@ccronje we can always help you with your RDA presentation. Not sure about the remote but that might be a possibility as well.

**Comment by arieldeardorff** [comment]
Can we close this issue folks?

**Comment by goldmj** [comment]
Yes @arieldeardorff. Maybe the proposal can still be used for something 🤷🏼‍♀️
