### ISSUE TITLE
Agenda Jan 2020

### ISSUE THREAD

**Issue by ragamouf** [LibraryCarpentry/governance#22]
Here's the beginning of an agenda for the January LCAG meeting. Please add your suggestions if there's anything you'd like to put forward for discussion. 

1. Introductions
2. Reportbacks from LCAG mini group goals
3. Ok we're merged, now what? Curriculum activities for 2020

**Comment by arieldeardorff** [comment]
I've got two things to add (will add to the Etherpad as well):
- Update on a project I will be working on to expand the Carpentries in California
- Touch base with Sher from the Carpentries about organizing workshops

**Comment by konrad** [comment]
- One super-minor status update regarding "Goal 1 Mini Group - Survey Library Carpentry Members"  (#19) - basically we have to wait for the release of the data of the currently ongoing survey.

**Comment by ragamouf** [comment]
Thanks @arieldeardorff  and @konrad - these are very welcome additions!

**Comment by ccronje** [comment]
@ragamouf for point 3 Curriculum activities, a few discussions from 2019 with @libcce that may help us kick off 2020:
- bringing more lessons to stable and determining which ones to prioritise
- checking in with maintainers and providing a process so they can alert us if they need our help (e.g. via a specific issue label)
- adding new curricula in https://librarycarpentry.org/lc-overview/ to the workshop forms https://amy.carpentries.org/forms/workshop/ and monitoring custom (mix & match) requests for trends

**Comment by libcce** [comment]
For the goal:

Map lesson material to library resumes/CVs/job descriptions/competencies

An idea I floated to @ragamouf @gitti1 is that we can put together a blog post with what information we have with the hope of inspiring conversations in the community.  Tim permitting, we can check with the Advisory Group what people think?

**Comment by arieldeardorff** [comment]
Now that we have successfully finished the meeting shall we close this issue @ragamouf?

**Comment by ragamouf** [comment]
hells yes!
