### ISSUE TITLE
Action plans when wrapping up the workshop

### ISSUE THREAD

**Issue by PhilReedData** [LibraryCarpentry/governance#23]
Last month, @uom-nilani, @CarleneB and I delivered a LC workshop at [Durham, UK](https://philreeddata.github.io/2019-12-11-durham/). It went very well. We collated some feedback and created issues in OpenRefine and in Data intro with these comments and will continue to work on them. There was a further item I would like to raise here about the structure and pedagogy, specifically about wrapping up. 

We ended the workshop by getting the learners to write some action plans for themselves, something they will do in the next two weeks, and/or something they will do in the next three months. This will give them some commitment to apply what they have learned in their job and continue embedding it into their practice. I typed up the ones people shared with us into the Etherpad. This was @CarleneB 's idea.

Is this kind of goal setting something that others have done, and something to suggest to all? We felt that it really lifted the mood; after running the advanced OpenRefine episode which many people found to be beyond their reach, we ended on something optimistic. We could add a few sentences to the [workshop overview home page](https://librarycarpentry.org/lc-overview/).

**Comment by libcce** [comment]
@PhilReedData @uom-nilani @CarleneB I like the idea of goal setting. It's happened to some degree when I've done one up, one down at the end of a workshop but I think it would be great if you could add this to the overview page. You might want to have a look at an LC talk that Carli Spina gave https://github.com/LibraryCarpentry/governance/blob/master/community-calls/2019-03-07-Spina-UDL.pdf and the video https://www.youtube.com/watch?v=56rhFeU5-Ig especially on multiple means of engagement.

**Comment by arieldeardorff** [comment]
I think this is a great way to end a workshop! I have been thinking for a while about better ways to end Carpentries workshops as it can be easy to just end the last lesson and peace out (especially as instructors and learners are usually pretty tired at this point). A couple of times we have had learners end with a think-pair-share about the most valuable thing they took from the workshop. I could see combining that with more concrete goal setting. The workshop overview page sounds like a good place to me!

**Comment by ragamouf** [comment]
I really like these goal setting activities too - I see them working really well in a think pair share, and I'd like to offer an experience I had that could support this activity. I was in a generic professional development workshop, and the facilitator followed up the goal setting exercise by asking us how likely we were to undertake that goal (eg 50,70, 90%), and then ask what would it take to make that likelihood 100%. In this way I realised learners could start to identify their own behaviours and support from colleagues/supervisors that could help them towards achieving that goal.
Thank you for sharing this idea!

**Comment by PhilReedData** [comment]
Thanks @arieldeardorff @ragamouf and @CarleneB -- I have added your ideas to a new section on the workshop overview homepage [in a branch](https://github.com/LibraryCarpentry/lc-overview/pull/20). It is a section following the four parts, listing three ideas for workshop leads to use about goals/reflection.

**Comment by arieldeardorff** [comment]
This looks great @PhilReedData!
