### ISSUE TITLE
Write a blog post about how to integrate LC lessons into curricula or reuse them differently

### ISSUE THREAD

**Issue by konrad** [LibraryCarpentry/governance#24]
In the LC Advisory group call 2020-01-21 we decided to write a blog post that covers the integration of LC lessons / content into curricula and alternative applications beside the workshops. @libcce, @jt14den and @jcoliver indicated interest in helping.  Feel free to put some discussion points here. I will then start a document (Google Docs or a file on GitHub).

**Comment by konrad** [comment]
I could report about different occasions where I used LC content (sorry, most of the following links are referring to German sites): I used the content for students of [MALIS](https://www.th-koeln.de/studium/bibliotheks--und-informationswissenschaft-master_3202.php) (Master in Library and Information Science) and for student of the bachelor "[Library and Communication](https://www.th-koeln.de/studium/bibliothek-und-digitale-kommunikation-bachelor_52771.php)" in two different formats (longer ones ~ 3 days or so and shorter one with a short intro into Python). A student of "Library and Communication" will work the Wikidata lesson for her bachelor thesis. Additionally, we got a grant at the TH Köln for implementing a [Data Literacy program](https://kisd.de/en/news/datenkompetenz-in-der-lehre-verankern-data-literacy-initiative-der-th-koeln-vom-stifterverband-ausgezeichnet/) across several faculties. We will also use Carpentry lessons there and ideally even help to develop more of them.

**Comment by arieldeardorff** [comment]
Thanks for getting the ball rolling @konrad! It sounded like @goldmj was using Library Carpentry materials for a class at Simmons so I am pinging her here in case she wants to contribute.

**Comment by konrad** [comment]
Thanks, @arieldeardorff! @goldmj, would be great if we could get your story as well.

**Comment by goldmj** [comment]
Happy to contribute! I haven't actually outlined what this would look like so I'll get my thoughts together!

**Comment by libcce** [comment]
We have a blog post [The Carpentries in the Classroom](https://librarycarpentry.org/blog/2019/01/carpentries-in-the-classroom/) which might be useful? I've heard from professors that there is so much customization in their courses that they can't see using an LC lesson. They might pull content and reuse it or use the examples. It might be valuable to work with student groups at library schools to coordinate LC workshops? Simmons has [ASIST](https://internal.simmons.edu/students/academics/slis/current/associations) and has been interested in training programs in the past. I've also spoken to professors where LC can be part of student practicums or projects where they go through certification to become trainers and work to improve lessons or work on new lessons. The more technical library courses like intro to information/databases have said they can use some of the lessons but sometimes there is missing content/lessons they need. I was excited about the practicum/project approach but never got further with it.

**Comment by konrad** [comment]
Thanks, @libcce - I forgot about that post. I think out new blog post would be close to that but covering further examples. Maybe one could even make a proper series out of it.

**Comment by libcce** [comment]
@konrad I like the series idea. Do we have enough stories for a series with @jt14den and @jcoliver? Seems like a better option than one long blog post and allows us to focus. Maybe @serahrono would be interested in this as well? I believe LC stories are now posted and tagged via The Carpentries site?

**Comment by jcoliver** [comment]
I think we could do a limited-run series, for sure. Each post could be relatively lightweight (1-2 paragraphs) and highlight LC wins?

**Comment by jcoliver** [comment]
Two topics that may be useful for brief, standalone posts:
+ Tidy Data is an awesome introduction to many data management best practices; modified from the DC Ecology lesson (I think), the data in the LC lesson are accessible to just about any audience. The materials could be deployed to incoming graduate students during graduate student orientation.
+ OpenRefine makes data munging a lot easier, especially when working with dates and there is a significant need for deduplication. This is also a lesson that could be delivered in a new graduate student orientation session.

**Comment by konrad** [comment]
I have generated a [document](https://docs.google.com/document/d/13PZGFcgpsGG-AgSM9aVeVVHsITbIy855U16Lo5E5c28/edit?usp=sharing) and added three sections. Depending how large they become we split them into different posts or have one joint post. @jcoliver, please feel warmly invited :wink:.

**Comment by jcoliver** [comment]
Do we have target dates for getting these out?

**Comment by konrad** [comment]
As decided today - deadline: 2020-04-24

**Comment by serahkiburu** [comment]
thanks @konrad and @jcoliver for working on this. I have added a note to get the post published in the last week of April. Whenever your draft is ready, please submit a PR to [GitHub.com/carpentries/carpentries.org](https://github.com/carpentries/carpentries.org)

**Comment by konrad** [comment]
Fantastic, thanks for being so proactive, @serahrono!

**Comment by jcoliver** [comment]
A draft of part 3 is on the Google Doc. Comments and edits are welcome.

**Comment by goldmj** [comment]
Loving the subtle date references, @jcoliver! 
My section has been fleshed out - a bit _longer_ than planned!
Please comment and feel free to suggest areas that could be left out/shortened.

**Comment by arieldeardorff** [comment]
Hey All! This draft is looking good! Anything you need from the group in order to move forward on this?

**Comment by PhilReedData** [comment]
I have written an [article about digital skills strategy for the Catalogue & Index journal](https://www.cilip.org.uk/members/group_content_view.asp?group=201298&id=861275), issue 198. This journal is run by 
the CILIP [Metadata and Discovery Group](https://catandindexgroup.wordpress.com/) (MDG, formerly Cataloguing and Indexing Group) who are looking at digital skills and communities of practice more broadly. (CILIP is the UK chartered librarian body.)

The article suggests ways to support their goals which also have a much wider potential. It explains the benefits and opportunities of Library Carpentry workshops in contributing to a community of practice for metadata and cataloguing professionals. It summarises the work that we have done in Manchester, UK to develop LC in the north of England. We had plans to run a workshop this summer for this group but COVID-19 has delayed us. We were looking at running it online instead but we are much busier than ever before with the 'day job' while we transform our core teaching to online delivery. It's particularly hard to make time for Carpentries development work here at the moment, I expect it may be for you too.

**Comment by jcoliver** [comment]
Per conversation in LC Advisory Group today, this is nearly ready to send to The Carpentries for posting. Want to bring it home, @konrad ?

**Comment by jcoliver** [comment]
I just reviewed my section, fixed a little grammar, and shook my fist at Google's suggestion that I use the singular conjugation for "data" (let your pedant flag fly, I say). I'm good to go on this!

**Comment by goldmj** [comment]
I have just finalized my section. It is quite long, so I welcome any careful review. But I thought it would be good to provide some student feedback on the lessons we reviewed. Good to go as well!

**Comment by konrad** [comment]
Many thanks @goldmj and @jcoliver. I have added a short intro on top and my part at the end and would need to know if the changes of the title of the section is okay. It would be fanatic if a native speaker could check my parts and ping me here shortly. I would suggest we publish this as one longer blog post the discussed alternative was a series of smaller posts). I can take care of converting the google doc into a markdown file in the [LC webpage repo](https://github.com/LibraryCarpentry/librarycarpentry.github.io) once I know we are good to go.

**Comment by goldmj** [comment]
Looks really good to me @konrad! I have added a link to our RDM curriculum on OSF :)

**Comment by jcoliver** [comment]
All looks good to me, including your section, @konrad .

**Comment by konrad** [comment]
Thanks, everybody! The [PR is submitted](https://github.com/LibraryCarpentry/librarycarpentry.github.io/pull/120).

**Comment by ragamouf** [comment]
Well done everyone! Adding the post for good measure - probably ok to close this issue?
https://librarycarpentry.org/blog/2021/03/integration_and_reuse_of_lc_content_into_curricula/
