### ISSUE TITLE
Draft report to library management outlining the benefits of joining the Library Carpentry/The Carpentries community.

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/governance#26]
Birgit was working with other members of The Carpentries community to develop a report. Birgit, did you ever complete/submit the report? I believe you were working with 3 other institutions, right? Or do you have an outline for us to start from? There is also some material here: https://github.com/LibraryCarpentry/governance/tree/master/proposals.

**Comment by arieldeardorff** [comment]
Thanks Chris! I mentioned that this could potentially be part of my project to expand the Carpentries in CA Libraries as well. Those proposals look like a great place to start! 

Tagging @gitti1 in case she didn't see the earlier mention.

**Comment by gitti1** [comment]
Hi both, 
we made a start and then did not find the time / energy to work this out... - here is what we gathered so far and I'd be glad if we could reuse some of the thoughts we collected (notes from our meeting in Jan 2019 put into a draft article structure): https://docs.google.com/document/d/1Cj7JVAkkF9aJpBWkaNE04sLr9_3LTdizwiq2WUV7Km8/edit?usp=sharing
Please let me know what you think. 

Have a nice Sunday, 
Birgit

**Comment by arieldeardorff** [comment]
This looks like the makings of a great article @gitti1! Do you want to put out a call for other co-authors from the Library Carpentry community? It might give you some new momentum.

I think this kind of case study article would be complemented by a shorter handout for Library admin. This Library Carpentry One pager (https://github.com/LibraryCarpentry/governance/blob/master/proposals/lir-heanet-pager.md) that @libcce and @davidfkane wrote is great and I think it just needs updating with a little more info on costs. I will take a stab at creating a new version of this. Ideally we could also include some of the impact stories that @elizabethwilliams8 is currently gathering.

**Comment by arieldeardorff** [comment]
Update: I created a draft and opened a pull request #28 (not sure that was the best way to organize everything but I think the proposals folder is a good place for this kind of stuff to live)

**Comment by arieldeardorff** [comment]
Update 2: I think my brain was going to break doing this as a markdown document in GitHub so I moved it to a [google doc](https://docs.google.com/document/d/19YrekJwkPgvucw1P9bNrhjznEbu9XHYN6AHoOOR9sk8/edit?usp=sharing) for editing with the goal of adding the finalized versions back to GitHub.

Please feel free to edit/comment!

**Comment by PhilReedData** [comment]
HI Ariel, that doc looks great.

Can we encourage library directors' buy-in by suggesting they use their Creative Commons-licensed digitized special collections in lessons? I've been adapting a Manchester TEI-XML training series to a [LC-style lesson](https://uomlibrary.github.io/workshop-tei/) which uses our own special collections as exercises/examples. I want to suggest this (unfinished) resource to the LC XML group as something which may be of use. 

Would it be appropriate for official LC lessons to use open resources in this way? I think I can use it to promote the Carpentries at my institution, and it may help at others if their staff can develop lessons and promote collections at the same time.

(I've put this on the end of the agenda for the Advisory Group next week. Happy to discuss it here instead if that's more appropriate.)

**Comment by arieldeardorff** [comment]
The letters are now posted in the proposals repo: https://github.com/LibraryCarpentry/governance/tree/master/proposals
