### ISSUE TITLE
Draft a letter of interest for funders to support greater involvement and inclusion in Library Carpentry.

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/governance#27]
We’ve had a number of grants lately funding Library Carpentry in USA/Canada. I wonder if this goal should be reframed to develop grants for other regions of the world that haven’t been able to host/run workshops? For instance, on my way out as the LC Director, there were several institutions in Southeast Asia that were trying to grow a community and I gave my remaining slots for online instructor training to them. We might want to reach out to them and see if there is funding in The Carpentries, other places to help them? South America is another region where I had some initial conversations, also stemming from my earlier days doing Data Scientist Training for Librarians.

**Comment by ragamouf** [comment]
Hi Chris, I would support that reframing. Matthias has been in contact with some folk in Malaysia who are planning LC workshops this year. I believe I was in that same online instructor training workshop too.

**Comment by libcce** [comment]
That's great. Depending on where the conversations go with them, we, members of the Advisory Group can be a resource for them.
