### ISSUE TITLE
RFC on installation instructions for LC workshop website

### ISSUE THREAD

**Issue by fmichonneau** [LibraryCarpentry/governance#29]
Hello all,

We have been working on updating the structure of the installation instructions that are included in the workshop website template.

For Data Carpentry workshops, the installation instructions are now removed from the workshop website template and are instead listed on the workshop overview page for each curriculum.

For Software Carpentry, we have a [pull request](https://github.com/carpentries/workshop-template/pull/664) to reorganize the files in the repository to make it easier for instructors to customize the installation instructions for the tools that they will cover during their workshop.

We haven't received feedback from the LC community about the proposed changes, and we would welcome your input on whether the LC community would like to explore how installation instructions included in the workshop template could be reorganized to facilitate setting up the website for LC workshops. Would the approach taken by either DC or SWC make sense for LC workshops?

Thanks!

**Comment by ragamouf** [comment]
Hi @fmichonneau, thanks for this. I can't answer this for myself, but have passed this on to the LC advisory group email list and will reach to the LC community.
