### ISSUE TITLE
LC Maintainer support survey 2020

### ISSUE THREAD

**Issue by ragamouf** [LibraryCarpentry/governance#31]
The Library Carpentry Advisory Group is keen to reach out to our maintainers to get a better handle on lesson maintenance and what we can do to support our maintainers.

This survey was open from 8 July to 24 July 2020, shared on the LCAG and discuss-library carpentries topicbox lists.

At 21 Aug 2020 we had 11 responses - 10 unique responders.

Quick summary
- most responses from North America
- overwhelming support for a LC maintainer call
- For: _What kind of support do you find yourself looking for in order to be a maintainer?_ most responses indicated guidance and documentation (91%), followed by community and networking (73%) and skills training (64%)
- Covid-19 pandemic affected maintainer either a little or a lot for about 2/3 of maintainers.
- Positive comments from those who participated in the recent Maintainer Onboarding programs
- Connecting to and giving back to the community were strong themes in what was best about being a maintainer
- Most (72%) responders intended to be a maintainer for 18months or longer
- Aspects of support to be improved were wide ranging and covered documentation & processes, building community and communication around significant lesson overhaul, organisation of lessons and topics.
- Other comments attested to difficulties in finding the time to contribute usefully.

Tab delimited table of responses (excluding name, email, city and timezone responses) available here.
[LC Maintainers support survey 2020.txt](https://github.com/LibraryCarpentry/governance/files/5106672/LC.Maintainers.support.survey.2020.txt)

Please contact @ragamouf if you would like access to the full dataset.

**Comment by ragamouf** [comment]
Surmising that maintainers are looking for community and networking opportunities and skills training in order to understand guidance and documentation for performing their roles.

Digging deeper into specific suggestions:
#### FIT FOR PURPOSE
help with identifying lesson use cases and coordinating communication with prospective [learners] who would be able to provide input on these.
#### GUIDELINES
standards, wiki
maintainer role turnover and refresh
#### Carpentries community
Pathways for maintainers -> Instructors 
Growing Instructor community to then build interest in becoming maintainers
#### Barriers / blockages for maintainers
Knowing who to ask for help (community)
Find time and space to work as a maintainer group on significant lesson and/or curriculum changes
Learning best technical practices for doing maintainer work (eg PRs, issues, workflows, etiquette)
#### Social side of lesson maintenance
Anguish over not contributing 'enough' or much over number of years
Am I doing this right?
Balancing personal expectations with availability (out of work time)

## Proposals for action:

1. Schedule a maintainers community call by Nov 2020 as a community networking and vision sharing session. Funnel people from this call into maintainer onboarding next year, see if there is interest in common goals for curriculum dev. 
2. Find out if the maintainer onboarding provides sufficient guidance and documentation
3. Schedule online git refresher workshops for maintainers in 2021 and other workshops from CarpentryCon eg Reverse Instructional Design - bring instructors and maintainers together?
4. Devise a plan for submitting lessons to the incubator or the other thing.

**Comment by libcce** [comment]
Tagging this previous issue https://github.com/LibraryCarpentry/governance/issues/10

**Comment by annajiat** [comment]
Skills training might become a priority as Jekyll may get phased out gradually.

**Comment by emcaulay** [comment]
LCAG discussed briefly at our Meeting 1 on 7/19/21. [notes](https://pad.carpentries.org/lc-advisory-group). We're going to review this issue as it relates to Curriculum matters (also on our agenda for today).

**Comment by ragamouf** [comment]
Woops! Reopening this until survey results discussed and future outcomes determined.
