### ISSUE TITLE
Rubric for assessing new member applications

### ISSUE THREAD

**Issue by ragamouf** [LibraryCarpentry/governance#32]
Opening this issue to collect feedback on further development on the membership application process to the Library Carpentry Advisory Group.

I want to emphasise that in developing the application form and working out how to assess applications, we are creating a new process, and it's not going to be perfect from the start, and that is ok!

Please use this issue to ask questions about assessing applications and using the rubric. We will refer to these in our 26/27 January 2021 meeting.

These are the questions I would like to bring to discussion with the group:
**Numbers**
- When there are more applicants than positions available (ie, people leaving), do we all vote and accept the most popular? Use a preferential voting system?
- What is the optimum size of the advisory group? How do we determine this?

**Purpose**
- When we assess these applications, do we want to rank candidates in a competitive process, or are we assessing their fit with the advisory group?
- For future rounds I would like to see a rubric shared with the application form, so that people have clearer outline of what we want applicants to answer. 
- How can we develop the process so that applying is a meaningful engagement, and everyone (successful/ unsuccessful applicants and assessors) comes away from the process having learnt something?  

**Decision making**
- Does everyone in the LCAG wish to assess the applicants? 
- Should we declare a smaller group to assess applications, and make recommendations which are ratified by the larger group? 

I welcome and look forward to your thoughts and comments!

**Comment by arieldeardorff** [comment]
I definitely agree with sharing the rubric in advance next time. 

One tweak to the rubric I might make for future rounds is to change the overall summary from yes/no/unsure to strong yes/weak yes/weak no/strong no or something similar. I found that there were lots of fine candidates with 1-2 standouts that I really wanted to push forward so a slightly different scale might make that easier.

**Comment by ragamouf** [comment]
Great point Ariel, I agree, this is a very blunt instrument, which would benefit from a little more nuance. Instead of 3 categories we could extend it to 5, ie where 1 is Red flag and 5 is outstanding. I found I wanted to distinguish between a strong/weak versions of does not meet criteria, and also meets criteria.

I also realised that the section about responses aligning with strategic goals could be confusing. Actually the rubric should refer to the About Us section on the LC page, as that is easier to answer, not "strategic goals" - since these are timebased and ephemeral.

**Comment by annajiat** [comment]
Well-written proposals, thank you @ragamouf  and @arieldeardorff 

Here are some quick thoughts:

**Numbers**
_- When there are more applicants than positions available (ie, people leaving), do we all vote and accept the most popular? Use a preferential voting system?_
Would Martha's law be suitable here? 
https://merely-useful.tech/py-rse/teams.html#teams-martha

_- What is the optimum size of the advisory group? How do we determine this?_
It might depend on:
1. availability of LCAG members.  
2. the amount of work and e.g., number of ongoing projects and LC needs that require addressing/pending projects. 
3. how much would we like to grow?


**Purpose**
+1 to both of those proposals


**Decision making**
Again, we wish to refer to Martha's law.
https://merely-useful.tech/py-rse/teams.html#teams-martha


I hope that helps.

**Comment by tobyhodges** [comment]
As I understand it, Martha's Rules are a good choice for decision-making within a team but not necessarily a great fit for an election. The inaugural election of the Trainer Leadership Committee was done via [Single Transferable Vote](https://electionbuddy.com/features/voting-systems/stv-voting), [as documented in the Trainers GitHub repository](https://github.com/carpentries/trainers/blob/main/governance.md).

**Comment by annajiat** [comment]
Thank you @tobyhodges for the guidance. I enjoyed learning about STV [electoral system](https://en.wikipedia.org/wiki/Electoral_system).
