### ISSUE TITLE
Create resource linking to communication channels for LCAG

### ISSUE THREAD

**Issue by jcoliver** [LibraryCarpentry/governance#33]
Especially for the purposes of onboarding new members to the group, a document could be created in this repo with links for getting connected to:

+ TopicBox (LC Advisory Group, Libraries)
+ Slack (#libraries)
+ Twitter (@LibCarpentry)
+ GitHub Governance repository (well, maybe not this, unless you love recursion)
+ LC Advisory Group Etherpad
+ Google community calendar

**Comment by arieldeardorff** [comment]
Hey @jcoliver totally agree we need something like this but I can't decide where it should live. What are your thoughts on creating a Wiki page here in the governance repo? I haven't used Github wikis before but it sounds like what we need.

**Comment by jcoliver** [comment]
Could probably start with a flat markdown file, CHANNELS.md, before going wild with a wiki. But if someone is keen to try out GitHub wikis...

**Comment by arieldeardorff** [comment]
I decided to add it to the [readme for our github repo](https://github.com/LibraryCarpentry/governance) so it wouldn't get too buried. Feel free to add any other links!
