### ISSUE TITLE
Publicize Library Carpentry Materials and Events/Workshops

### ISSUE THREAD

**Issue by annajiat** [LibraryCarpentry/governance#37]
In relation to the discussion in the LCAG meeting July 2021 which is also related to #35 by @chennesy and #36 by @egrguric ,

- [ ] We might wish to explore if we can pave the way for LC lessons to be used in non-carpentries workshop/environment who may or may not be familiar about the carpentries.
- [ ] We might want to make the materials more usable/accessible for self-learning by individuals.
- [ ] LC events welcoming external participants may be submitted for listing to different places e.g., in [US-RSE list of resources/events](https://us-rse.org/events-training/).
- [ ]  Is there any way to indicate acceptance of external participants, may be in the workshop title using a suffix "public" or something like "open to participants in some region"?

Thank you @libcce for the encouragement.

**Comment by egrguric** [comment]
Happy to help and cross pollinate from [#36](https://github.com/LibraryCarpentry/governance/issues/36)
