### ISSUE TITLE
Align LC Curriculum Advisory Committee with Core Team efforts to refresh CACs across the Carpentries

### ISSUE THREAD

**Issue by ragamouf** [LibraryCarpentry/governance#38]
The purpose of this goal is to strengthen the relationship between LC curriculum development and other Curriculum Advisory Committees across the Carpentries.

**Comment by ragamouf** [comment]
Tagging @PhilReedData as I don't know how to assign you to this issue.

**Comment by ragamouf** [comment]
@chennesy I think this can be closed once the LC CAC meets in 2022.

**Comment by chennesy** [comment]
@ragamouf It looks like I'm unable to close this one - but (as you know) LC-CAC met! Can you close this issue for us? thx
