### ISSUE TITLE
Review Pre & Post Workshop Surveys

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/governance#4]
Governance Group,

Before our next meeting, please review the LC pre and post surveys, give feedback in the issue, and vote if you think the surveys are ready to use. The history behind the surveys can be found here https://github.com/data-lessons/librarycarpentry/issues/20. This is before my time, but I believe the following surveys have already been approved by members of the LC community. We need to formalize them.

LC Pre-Workshop Survey:
https://www.surveymonkey.com/r/lcpreworkshopsurvey?workshop_id=[workshop_id_value]

LC Post-Workshop Survey:
https://www.surveymonkey.com/r/lcpostworkshopsurvey?workshop_id=[workshop_id_value]

PDF print outs of the questions can be found in the surveys folder:
https://github.com/LibraryCarpentry/governance/tree/master/surveys

**Comment by libcce** [comment]
Maneesha and Sher! will not include the surveys in workshop planning until we have approved them. The survey questions appear to have been copied over from Data Carpentry. @weaverbel notes that we should keep the survey brief. @libcce notes whether we should ask about training impact in the post-survey, how they might use the training in their work, and whether we should ask curriculum questions, to help us with future lesson development and to refine the core of the program. Once we've collected enough feedback, the surveys will be updated and shared with Kari for her review.

**Comment by Kakaalikins** [comment]
The pre-workshop survey could definitely be shorter, I think the post survey is fine in length. I also think the survey content needs to be edited in several areas to be more relevant to library and support staff. Some suggestions:

**Pre-workshop survey feedback:**
Q#6 could include different library roles?
Q#8 could add OpenRefine, regex?
Q#13 could be re-written entirely to include statements for relevant to support staff, as opposed to academic staff

**Post-workshop survey feedback**
Q#6 could be re-written as described in #13 above

**Comment by libcce** [comment]
For the post-workshop survey feedback, I suggest the following changes: 

For question 5, change to "What was covered in your workshop?" and include current LC lessons. For question 6, remove "Having access to the original, raw data is...", replace "I can write a small program/script/macro..." with "I can use what I learned in the workshop...", remove "programming" from "While working on a programming project...",  replace "Using a programming language (like R or Python) can make my analyses easier to reproduce." with "Using programming software can make my work easier.", remove last question

**Comment by libcce** [comment]
For the pre-workshop survey feedback, I suggest the following change:

For question 12, change to "Which of the following lessons is being covered in your workshop?" and then list current LC lessons.

I also have a question:

For question 8, do we need to add a question about programming and data software (Excel, OpenRefine)?

**Comment by pitviper6** [comment]
Pre-workshop survey:

For question 13, add something like "I am comfortable analyzing datasets for format, consistency and best data practices" and "I am comfortable using regular expressions and GREL for data manipulation and cleanup."

Post-workshop survey:

Same thing as above for question 6.  For question 5, add "Regular Expressions/GREL" as an option.

**Comment by kariljordan** [comment]
My only recommendation is that you be sure that the learning objectives line up with the questions being recommended here. Great recommendations, as I'm not extremely familiar with LC's curriculum. Thanks!

**Comment by jt14den** [comment]
For No. 5 - include something like **information science** 

**Pre-survey**

On number 13 of, instead of: 

>* "While working on a programming project, if I get stuck, I can find ways of overcoming the problem."
>
>Use something like: 
>
>* While working on a technical project, if I get stuck, I can find ways of overcoming the problem.

And: 
> * I am confident in my ability to make use of programming software to work with data.
> To: 
> * I am confident in my ability to make use of spreadsheet and analytic software to work with data in a reproducible fashion.

**Comment by jt14den** [comment]
Or maybe include on number 12, something like: 

>* If asked, I can easily reproduce all the actions I've made to a dataset for a project.

**Comment by kariljordan** [comment]
@maneesha added the question to SWC and DC surveys where the respondent has to copy and paste the workshop slug into the box. I just put a task in Asana for her to add that to LC surveys in SurveyMonkey, as I'm not sure how to do that. Once she adds that question I will remove the question that asks which workshop did you attend.

**Comment by libcce** [comment]
Surveys added to workshop template at https://github.com/carpentries/workshop-template/blob/gh-pages/_config.yml and https://github.com/carpentries/workshop-template/blob/gh-pages/index.md

**Comment by kariljordan** [comment]
Hello @libcce et al.

I want to re-open this issue because we are planning to release learner assessment reports in Q4 of this year and planning to move all of our surveys from SurveyMonkey to Typeform.

I'd like for the pre and post workshop survey for our lesson programs to be as consistent as possible. I realise there had been hesitation around questions using the phrase "programming language" and some of the other language, but I find that even for Library Carpentry workshops that are not programming based, these participants may have a perspective on these concepts.

[Here is the current Library Carpentry Pre-Workshop Survey](https://github.com/carpentries/assessment/blob/master/learner-assessment/surveys/lc_presurvey_current.pdf)

[Here is the current Data and Software Carpentry (common) Pre-Workshop Survey](https://carpentries.typeform.com/to/wi32rS?slug=xxxxx) 
- You can scroll through most of the questions without answering them

Are you opposed to Library Carpentry using the common survey for workshops?

cc @fmichonneau as he's working with me to get all of our surveys migrated over to Typeform.

**Comment by katrinleinweber** [comment]
If the voting options in https://github.com/LibraryCarpentry/governance/issues/16 can get their own names (similar to the different DC curricula), should they be added as answers in Q `4 -> Which of the following workshops are you attending?`.

Side note @kariljordan: "Mac OS X" [is now called "macOS"](https://www.apple.com/macos/) ;-)

**Comment by kariljordan** [comment]
The workshop admin team along with @fmichonneau are working on being able to identify which workshop a learner is attending by having a slug in the workshop website, so pretty soon we are going to omit the question where we ask learners what workshop they're attending. We'll know the answer already. Were there any other concerns about the rest of the questions? Thanks for the tip about Mac. @fmichonneau has revised that question as well (macOS, Unix, Windows are the options for "what operating system...")

**Comment by kariljordan** [comment]
Hello again. We'll be transitioning from SurveyMonkey to Typeform for our surveys, and I'm circling back to make sure this group is on board with us moving to one common survey for SwC, DC, and LC. I haven't heard any objections, and I've addressed @katrinleinweber's comment from July 20th, so we're moving forward! Thanks all.
