### ISSUE TITLE
Review Audience Page

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/governance#5]
The audience page is ready for your review:

https://librarycarpentry.github.io/lc-overview/audience/index.html
or https://github.com/LibraryCarpentry/lc-overview/tree/gh-pages/_episodes

Are we missing anything? Please add any modifications you think are necessary. 

We will encourage others to add to the list of demographic and job description resources pages, but feel free to add additional resources in the meantime.

**Comment by mhayslett** [comment]
I'm really pleased with this.  The diverse use cases and explanations of how the workshops & community can help subject librarians will be very helpful when we go to sign people up for our LC workshop.

**Comment by Kakaalikins** [comment]
This is really great, thanks @libcce 

Nothing to add right now, but will suggest additions as they arise :)

**Comment by davidfkane** [comment]
I would like to see the 'general profiles' to evolve more into fictitious personae.  We could start by removing the 'someone who is wishing...' and instead give each line a title.  For example the first line could read:

> **The Library Manager:**
> Wishes to understand how information and data are created and used both internally and externally at an organization to develop reports that help improve the quality of their data and services. (Reporting)
> 

Besides Library Manager, the others might be named: 

> _Curator, Archivist, Research Support Librarian, Teaching Librarian, I.T. Technician_

**Comment by libcce** [comment]
@davidfkane initially, that is what @pitviper6 and I were thinking but then we tried to continue the theme of not exactly confining this to professional, staff, etc roles and not entirely to libraries. What do others think?

**Comment by davidfkane** [comment]
I agree with you on not being restrictive regarding libraries, professional grades etc. but if you give these personae actual names - whoever they are - then you can cover 90% of the potential audience.  It also gets more real when you are dealing with personae - it's a well known marketing technique.

**Comment by libcce** [comment]
@davidfkane @pitviper6 @Kakaalikins @mhayslett I wonder if we should include a definition of what we think constitutes a librarian and incorporate inclusive language into that definition? I'm asking because I think it will help with the language I need to update throughout the Carpentries pages and for us to use simply the term librarian(s). I will be most likely changing every sentence that says "researchers" to "researchers and librarians".

**Comment by pitviper6** [comment]
I think that may open up a can o' worms? Through my 20 year library career there's nothing that starts massive arguments more than trying to define what a librarian is. My reasoning behind not including titles is that titles have always been a real source of conflict in libraries (professional vs. staff; e-resources or digital services librarian vs. IT etc.) and what any given person with a certain title may actually do can vary radically from library to library. I know this happens in all professions, but it seems especially egregious in library world. Maybe we can try it and see what the reaction is because I get the point about titles creating engagement/recognition in people.

**Comment by libcce** [comment]
@pitviper6 So maybe the easiest thing to do is to change the language to "researchers and librarians" on The Carpentries site, and when possible link to our audience page. Sound good for now?

**Comment by pitviper6** [comment]
That works for me!

**Comment by mhayslett** [comment]
I agree.  Using "librarian" at all will require explanations here that it is meant to include anyone working in our libraries, not just those who have an MLS.

**Comment by weaverbel** [comment]
Maybe we should say "people working in library- and information-related roles" to make it as broad as possible. I have commented elsewhere on not updating the Carpentries' definition for now - that mission and vision will be set by the Carpentries' Executive Council and won't include the language @libcce has suggested above at this stage.

**Comment by libcce** [comment]
and @weaverbel I continue to mention to you that it doesn't hurt to ask these questions in preparation.

**Comment by mhayslett** [comment]
I like @weaverbel 's suggestion.  That would mollify audiences here at UNC.  @libcce absolutely--it's good to figure out stuff like this in advance.

**Comment by libcce** [comment]
@mhayslett i'm glad you said that, i think that language, "people working in library- and information-related roles" could be ultimately what we use when we update language throughout. Seems like it reflects what we were attempting to convey in the audience page. thanks @weaverbel

**Comment by pitviper6** [comment]
I like that phrasing! Very general but gets the idea across.

**Comment by tracykteal** [comment]
This is a great discussion, and it is good to discuss these things! A few points

- The Executive Council is drafting mission and vision, with a Request for Comments coming soon. Based on this conversation and others, they already are including language that is inclusive beyond 'researchers' in mission and vision.  
- Independent of this, Library Carpentry has its audience and description for its website and how it is planning to describe itself, as Data Carpentry and Software Carpentry do. So what you decide here about audience is necessary and important for that.
- Even though The Carpentries mission and vision is coming together still (and apologizes for the interim confusion), for now we could update the header on the website from "We teach foundational coding and data science skills to researchers worldwide" to "We teach foundational coding and data science skills to the research community worldwide". If that would better represent the research library community, as an interim solution, I'll bring that to staff to discuss for an update.

Thank you for this discussion!

**Comment by libcce** [comment]
thanks for the update @tracykteal and the interim language you suggested sounds great to me.

**Comment by libcce** [comment]
Audience page is now available at https://librarycarpentry.org/audience/
