### ISSUE TITLE
Python lesson development

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/governance#6]
At CarpentryCon, several people discussed whether we should extend the current LC Python lesson
https://github.com/LibraryCarpentry/lc-python-intro to include more introductory, intermediate, and advanced material. There have also been some suggestions via the Gitter Lobby and lesson dev about incorporating more XML/JSON examples in the Python lessons. The following are suggestions of resources that can help as we consider this:

@weaverbel Brian Avery from Portland instructor training's lessons:
https://reproducible-science-curriculum.github.io/data-exploration-RR-Jupyter/

@libcce Rahul Dave's Data Scientist Training for Librarians 3-day Python program:
https://github.com/rahuldave/dst4l3
Note: DST4L was going to include more mapping/GIS as part of the Python lessons as it was well received

@ccronje Mentioned Programming Historian as a potential resource:
https://programminghistorian.org/en/lessons/

Please add your thoughts to this thread:

**Comment by jt14den** [comment]
I also like https://swcarpentry.github.io/python-novice-gapminder/. It does some intro to the language but gets into pandas and plotting before noon on the first day.  +1 to the Brian Avery lesson for having **tidy data**, we already use this concept in @jezcope's https://github.com/LibraryCarpentry/lc-spreadsheets. It would be good if we could thread this concept throughout our data oriented lessons.

**Comment by libcce** [comment]
Library Carpentry Python Lesson Maintainers are now addressing lesson development.
