### ISSUE TITLE
Carpentries Venn Diagram

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/governance#8]
It's time for us to determine how Library Carpentry fits within the Venn diagram on this page:
https://carpentries.github.io/instructor-training/20-carpentries/

My suggestions:

Outside the overlap:
Audience: People working in library- and information-related roles
Domain focus: Library and information science
Flexible, one-multi day curriculum centered around core objectives and lessons

Overlap:
volunteer instructors from research communities
research-focused, computational skills, addressing gaps
(not including two-day workshops)

@jt14den @ccronje @erikamias @katrin @katrinleinweber @laufers, thoughts? Others?

**Comment by laufers** [comment]
I would keep the idea of a two day workshop worth of content. If you look at the time of the first four lessons (https://librarycarpentry.github.io/lc-overview/) it takes two days. I would then add in the "out of circle" comment on flexible scheduling, modular, to facilitate multi-day scheduling, etc. 

My thinking on this is if offered at a conference setting, you would schedule for two days pre or post conference or 2 days imbedded?

**Comment by libcce** [comment]
@laufers I'm fine with your suggestion. In my conversations with Carpentries staff, there has been a preference for being more definitive though. If others agree, we can try to submit it as you suggest and see what they say.

**Comment by erikamias** [comment]
I support Chris' text suggestion for the venn diagram and @laufers
suggestion, let's see what the Carpentries staff say.

**Comment by ccronje** [comment]
Taking above comments into account:

Outside the overlap:
Audience: People working in library and information-related roles
Domain focus: Library and information science
*Modular curriculum centered around core objectives and lessons
*Flexible scheduling

Overlap:
Research-focused, computational skills, addressing gaps
Two-day workshops*
Volunteer instructors from research** communities

** 'research and library communities' may be more appropriate here?

**Comment by libcce** [comment]
Looks good @ccronje! Let's go with your version. @jt14den @katrinleinweber anything to add? Otherwise, we can close this issue and submit this request.

**Comment by erikamias** [comment]
Hi everyone, I did a mock-up of my understanding of how LC fits in the Venn diagram taking everyone's contributions into account, see attached:
![lc_venn_screenshot_v2](https://user-images.githubusercontent.com/21195620/44423218-d8b87200-a585-11e8-9b2b-d946019b4c4f.png)

**Comment by libcce** [comment]
@erikamias the diagram looks great. Thanks! I think we are just waiting on @jt14den now, but I think you should design the next iteration of the Venn diagram!

**Comment by laufers** [comment]
Novice level instruction is part of the SWC as well. All of our SWC workshops at OU have been for beginners with no experience.

**Comment by ccronje** [comment]
Looks great @erikamias - @laufers perhaps we could move 'novice-level training' into the middle, as it applies to all, and have the green 'domain focus'.

**Comment by jt14den** [comment]
@erikamias thanks for the chart! I agree with @laufers about SWC being for novices and with @ccronje about moving it to be shared. 

One thing I'd recommend is to change "Collections and information support" to "Collections and research support". We have information well represented, but need something that reflects supporting more diverse set of practices and tools beyond informational.

**Comment by libcce** [comment]
Thanks @jt14den! I think that sticks a fork in this. The only thing left is if @erikamias can modify the Venn diagram that she created to reflect these changes? It is so much better than the Venn diagram there now! Thanks everyone!

**Comment by jezcope** [comment]
I'd be inclined to finesse the domain focus a bit to work archives and museums in there either explicitly or implicitly, but I think that can wait for future iterations of this diagram. It looks good to go content-wise.

**Comment by erikamias** [comment]
No problem, work on it and upload for review asap.

**Comment by erikamias** [comment]
![screen shot 2018-09-20 at 20 19 52](https://user-images.githubusercontent.com/21195620/45838760-d8d99800-bd12-11e8-98c7-392146422583.png)

![screen shot 2018-09-20 at 20 27 47](https://user-images.githubusercontent.com/21195620/45839094-ae3c0f00-bd13-11e8-9a89-44d1b3218d9c.png)

Hi everyone, how is this for content? (Original venn included for comparison) The text is a bit fiddly in these shapes so will post options for style/colours/layout if this text is ok?

**Comment by erikamias** [comment]
Style Option 2
![screen shot 2018-09-20 at 21 36 06](https://user-images.githubusercontent.com/21195620/45842540-45599480-bd1d-11e8-879c-64b95201835a.png)
![screen shot 2018-09-20 at 20 27 47](https://user-images.githubusercontent.com/21195620/45842555-4f7b9300-bd1d-11e8-8de3-bdae6fbc4f2f.png)

**Comment by katrinleinweber** [comment]
I prefer the lighter-colored, 2nd style. The 🛡-like white part in the middle brings up some nice connotations :-)

Are the source files git- and collaboratively edit-able?

**Comment by libcce** [comment]
I like the 2nd style but just wondered about color contrast and people who are color blind https://www.toptal.com/designers/colorfilter/ So the first option might be better?

**Comment by katrinleinweber** [comment]
Thanks for this tool suggestion :-) As far as I understood color blindness, clear edges/borders alleviate the problem of low contrast. Neither style relies on color alone to group the sections, but uses the white circumferences to make it absolutely clear.

Hence, I think we are free to focus more on the wording and the style that best fits to the page/site on which the diagram should eventually appear. That's what I assumed to be the rating criteria, aren't they?

**Comment by erikamias** [comment]
Link to the editable doc is here: https://docs.google.com/presentation/d/19Cp3FBH1812TDF6LuQCQ_zg0tXOTISqcHaVXQj7oMiQ/edit?usp=sharing

Regarding the colour blindness, I asked my partner to have a look (he has red/green colour blindness) and he says that option 1 and 2 both are easy for him to read but his preference is for option 2 (the light coloured one) because the text stands out more. 

I think we can make whichever option we don't use for the website available as an alternative for folks who want to inlcude the diagram in a Carpentries presentation if they like?

(I designed the pale one so it is clear how it evolves from the original Venn, the the bold one is a more vibey though)

**Comment by libcce** [comment]
@tracykteal what do you think of the new Venn diagram for the instructor training material that @erikamias created based on our feedback? We have two votes so far for the 2nd style.

**Comment by jezcope** [comment]
I'll add a third vote for the second. Thanks for your work on this so far @erikamias!

**Comment by jt14den** [comment]
I also like the 2nd! Thanks @erikamias!

**Comment by tracykteal** [comment]
Me too for the 2nd. That's great! Thanks @erikamias

**Comment by raynamharris** [comment]
The 2nd Venn diagram is awesome! I would be great to include it in the TTT lesson materials. We can update the language in this section if necessary:
https://github.com/carpentries/instructor-training/blob/2a67c897ead5d0eb80edd6388b760d18d2806ffa/_episodes/21-carpentries.md#similarities-and-differences-between-the-carpentries-lesson-programs.

**Comment by ChristinaLK** [comment]
@erikamias or anyone on this thread -- is there a jpeg/png/svg version of this venn diagram image?

**Comment by erikamias** [comment]
Is this ok (needs a bit of cropping on the sides probably)? Can't upload the svg file butI can send it to you seperately if you like? 

> @erikamias or anyone on this thread -- is there a jpeg/png/svg version of this venn diagram image?

[carpentries-venn-diagram_20190522.pdf](https://github.com/LibraryCarpentry/governance/files/3207926/carpentries-venn-diagram_20190522.pdf)
![carpentries-venn-diagram_20190522](https://user-images.githubusercontent.com/21195620/58184571-5d543000-7c7f-11e9-9542-f23200190169.jpg)
![carpentries-venn-diagram_20190522](https://user-images.githubusercontent.com/21195620/58184580-5f1df380-7c7f-11e9-96a6-823ff6b0b722.png)

**Comment by erikamias** [comment]
![carpentries-venn-diagram_20190522](https://user-images.githubusercontent.com/21195620/58184871-ef5c3880-7c7f-11e9-9827-79996ddd04cf.jpg)

**Comment by erikamias** [comment]
jpg
![carpentries-venn-diagram_20190522](https://user-images.githubusercontent.com/21195620/58184913-0569f900-7c80-11e9-81c5-8323e6f58c65.jpg)

**Comment by ChristinaLK** [comment]
You are fast! Can you email the svg to ckoch5@wisc.edu?

**Comment by arieldeardorff** [comment]
Hey All! Since it looks like this beautiful diagram is now posted on the Carpentries site can we close this issue?

**Comment by libcce** [comment]
I think I might be guilty of leaving this open. Yup, this is old. Thanks for catching this @arieldeardorff!
