### ISSUE TITLE
Technical aspects of Maintainer Onboarding

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/governance#9]
- [ ] learn https://carpentries.github.io/maintainer-onboarding/03-technical/index.html by Dec. 1st
- [ ] prepare to record a summary by early Feb'19
- [ ] send PRs, if LC-relevant updates are needed
- [x] ~~check if [project boards](http://help.github.com/articles/about-project-boards/) would be suitable~~ out of scope; stick to GH issues & PRs
- [ ] Prepare to install Jekyll & Atom on a fresh computer (assume Git already is installed)
- [ ] GitHub web interface: outdated `list-serv` => commit directly, because broken
     - [remove "Some introductory text" & "Some group discussion to end." in `02-curricular`](https://carpentries.github.io/maintainer-onboarding/02-curricular/index.html) => to separate branch for discussion in PR
    - outdated link in [`03-technical`](https://carpentries.github.io/maintainer-onboarding/03-technical/index.html#style-maintenance) => could become issue as [opportunity for novices to engage in `legitimate peripheral participation`](http://teachtogether.tech/en/community/ or offline plus `make serve` to preview, try `make -B serve`
        - `http` to `https` or `swcarpentry` to `carpentries` in all files
- [ ] [`Good commit messages`](https://swcarpentry.github.io/git-novice/04-changes/index.html) plus [closing keywords](https://help.github.com/articles/closing-issues-using-keywords/)
    - emphasise need to keep changes atomic
- @libcce: also [checking out PR locally](https://help.github.com/articles/checking-out-pull-requests-locally/)?

**Comment by libcce** [comment]
@katrinleinweber this seemed to be sufficient for onboarding purposes https://github.com/LibraryCarpentry/governance/blob/master/curriculum/2019-01-20-summary-maintainer-discussions.md Individual LC Maintainer teams will meet to address technical aspects if necessary.
